### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by 0xtfa** [victor-lillo/react-confirm-toast#2]
How can I customize a theme? I can probably override existing themes, but can I create a new one? If yes, then how?

**Comment by victor-lillo** [comment]
Hello!

Just create a CSS class and pass it through `childrenClassName`. [There](https://github.com/victor-lillo/react-confirm-toast/blob/main/src/components/ConfirmToast/ConfirmToast.module.scss), you can override the custom properties to customize the theme.

By the way, I'm working on new version of this package, feel free to suggest features if you want :)

Thanks!

**Comment by 0xtfa** [comment]
I'm a little bit confused on how to do it. Could you give me an example please? Thank you for your support!

**Comment by victor-lillo** [comment]
Sure, @synpse!

Follow this steps:

1) **Create a CSS class** in one of your stylesheets with the custom theme you want. For example:

```css
.custom-confirm-toast-theme {
  --confirm-toast-bg: aquamarine;
  --confirm-toast-msg-color: purple;
  --confirm-toast-icon-color: black;
  --confirm-toast-btn-yes-color: lightgreen;
  --confirm-toast-btn-no-color: pink;
  --confirm-toast-btn-yes-bg: green;
  --confirm-toast-btn-no-bg: crimson;
  --confirm-toast-btn-hover: 0.9;
}
```

2) **Pass this class name** to the `childrenClassname` property, like this:

```jsx
<ConfirmToast
  childrenClassName='custom-confirm-toast-theme'
  // Rest of the props you need
>
  <button>Your component</button>
</ConfirmToast>
```

And with this you are done! 

![image](https://github.com/victor-lillo/react-confirm-toast/assets/68304662/3c4988c8-e604-4f54-b3ca-73e5e63dcf7b)
